### ISSUE TITLE
Not compatible with Django 3.1

### ISSUE THREAD

**Issue by yapper-git** [alrusdi/django_digg_paginator#1]
I updated my django version to 3.1.1 but django-digg-paginator est incompatible with this version of django.

```
  File "zzz/views.py", line 4, in <module>
    from digg_paginator import DiggPaginator
  File "zzz/venv/lib/python3.8/site-packages/digg_paginator/__init__.py", line 4, in <module>
    from .paginators import ExPaginator, DiggPaginator, QuerySetDiggPaginator
  File "zzz/venv/lib/python3.8/site-packages/digg_paginator/paginators.py", line 3, in <module>
    from django.core.paginator import \
ImportError: cannot import name 'QuerySetPaginator' from 'django.core.paginator' (zzz/venv/lib/python3.8/site-packages/django/core/paginator.py)
```
According to the release note, "django.core.paginator.QuerySetPaginator is removed."

see https://docs.djangoproject.com/en/dev/releases/3.1/#features-removed-in-3-1

Do you plan to update your package ?

**Comment by alrusdi** [comment]
I don't use it anymore. But upgrade is seems to be trivial. I can do it if you really need it.

**Comment by yapper-git** [comment]
I use it in several projects. I'd be glad if you upgrade it :)

**Comment by alrusdi** [comment]
> I use it in several projects. I'd be glad if you upgrade it :)

Can you test some of your projects against current master branch?

**Comment by yapper-git** [comment]
I tested current master branch using `-e git://github.com/alrusdi/django_digg_paginator.git#egg=django-digg-paginator`
I can confirm that it works correctly for me!
Thank you very much for your rapidity and your great help!

Can you release a new version in pip please?

**Comment by alrusdi** [comment]
Done
